### ISSUE TITLE
INFOGRAFIA DE LIBRERIA

### ISSUE THREAD

**Issue by JudithReynaCS** [SistemasTecTlaxiaco/infografia-de-las-librerias-JudithReynaCS#2]
[Infografía Librería_JudithReynaCruzSantiago_4US.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-JudithReynaCS/files/8211458/Infografia.Libreria_JudithReynaCruzSantiago_4US.pdf)

**Comment by Adry117** [comment]
Calificación 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
